version: '3'
services:
  app:
    image: jsaponara/vcard-database
    container_name: vcard-database
    ports: 
      - 80:80
    build:
      context: . 
      dockerfile: Dockerfile
    volumes: 
      - .:/app
      - ${DIR}/nginx:/var/log/nginx
    